<?php

include("./config.php");

$acc = $_POST['acc'];
$pwd = $_POST['pwd'];



if ($_POST) { # "@" : error messages that might be generated by that expression will be ignored.
    if ($_POST["method"] == "login") {
        $sql = "SELECT * FROM `users` WHERE `account`= '$acc'";
        $result = mysqli_query($link, $sql);
        $rows = mysqli_num_rows($result);
        if ($rows > 0) { # 有這個帳號
            $sql_pwd = "SELECT * FROM `users` WHERE `account`='$acc'AND`password`= '$pwd'";
            $result_pwd = mysqli_query($link, $sql_pwd);
            $rows = mysqli_num_rows($result_pwd);
            if ($rows > 0) { # 密碼正確
                $_SESSION["name"] = "$acc";
                echo "1";
            } else { # 密碼錯誤
                echo "0";
            }
        } else { #未註冊
            echo "-1";
        }
    }
    if ($_POST['method'] == "register") { # 要求註冊
        $sql_check = "SELECT * FROM `users` WHERE `account` == '$acc' ";
        $check = mysqli_query($link, $sql_check);
        $rows = mysqli_num_rows($check);
        if ($rows > 0) { #檢查是否帳號重複
            echo "2";
        } else {
            $sql_insert = "INSERT INTO `users` (`account`, `password`) VALUES ('$acc','$pwd')";
            $insert = mysqli_query($link, $sql_insert);
            if ($insert) {
                echo "3";
            }
        }
    }
}
